Fix " Dino does not add own account to roster"
mxlgv/dino pull request #58
Opened 2024-04-17 09:59 UTC by Psayker

Add yourself to roster

![image](https://github.com/mxlgv/dino/assets/32624465/b0758f34-be5f-4aad-974a-987f1abb5d4a)

2024-04-17 11:23 UTC, mxlgv requested changes

2024-04-17 11:23 UTC, mxlgv commented on main/src/ui/add_conversation/roster_list.vala
> +        foreach (Account a in accounts){
Please fix codestyle: `foreach (...) {`

2024-04-17 11:23 UTC, mxlgv commented on main/src/ui/add_conversation/roster_list.vala
> +            ListBoxRow own_account_lbrow = new ListBoxRow() { child=own_account_row };
Please fix codestyle: `child = own_account_row`

2024-04-17 12:41 UTC, mxlgv commented on main/src/ui/add_conversation/roster_list.vala
> +        foreach (Account a in accounts){
@Psayker now `(` is stuck to `foreach`

2024-04-22 07:53 UTC, Psayker commented on main/src/ui/add_conversation/roster_list.vala
> +        foreach (Account a in accounts){
done

2024-04-24 14:25 UTC, mxlgv approved these changes

2024-04-24 14:25 UTC, merged